### ISSUE TITLE
Double monitor, double layout usage

### ISSUE THREAD

**Issue by umitarabul** [suurjaak/InputScope#2]
I am using two monitors and the main monitor is vertical and side monitor is horizontal. I have tried to move the mouse around the corners to obtain the boundaries of the monitors. However it does not seem correct. See the image.

![mouse_statistics](https://cloud.githubusercontent.com/assets/1573441/26347485/06dd9fae-3faa-11e7-8f4a-04be2db8cac9.PNG)

Do you handle the multiple monitor case?

**Comment by suurjaak** [comment]
I'm sorry, I have no idea how I managed to not notice for so long that there are open issues on this project. 

No, multiple monitors are currently totally unsupported. Is this something you're still interested in?

**Comment by shenef** [comment]
I would be interested in that.
The setup i'm using has three monitors where each of them has a different size and iirc in my testing a few months back it seemed like as if the mouse movements on all screens are overlayed on top of each other.
Screens from left to right: 1920x1080, 2560x1080, 1600x900
It's a weird setup and i can fully understand if it won't get full support.

**Comment by suurjaak** [comment]
>  it seemed like as if the mouse movements on all screens are overlayed on top of each other

Yep, as the program currently assumes a single display, all mouse movement is mapped onto a single target in program statistics. 

I think that if multiple monitor support can be added, it will work also if there are more than 2 monitors. 

But just to check, can you do the following on your three-monitor system:

- run InputScope
- right-click on the tray icon and choose "Show Python console"
- in the console window, execute `for i in range(wx.Display.GetCount()): print i, wx.Display(i).Geometry`

What is the result?

**Comment by shenef** [comment]
The Output is:
```
0 (0, 0, 2560, 1080)
1 (-1920, 0, 1920, 1080)
2 (2560, 237, 1600, 900)
```
i guess the third one has the shift of 237 cause it has a lower stand and that's how i adjusted it in the windows display settings

**Comment by suurjaak** [comment]
The new v1.3 release has support for multiple displays. 

Can you confirm it works on your setup?

**Comment by shenef** [comment]
On 1.3 and 1.4 multi monitor seems to work great.
The only "problems" i found so far is that the heatmap preview is stretched to 16:9 and on my rightmost monitor the capture speed seems to be lower than on the other screens (though that screen is the oldest and the only one connected via DVI)

**Comment by suurjaak** [comment]
Excellent, glad to hear it's working as intended. 

Yes, mouse heatmap is always scaled to 16:9 - because a display can have any number of resolutions applied on it over time. But perhaps in a next release I will use the scale of the first recorded screen size, as anyway most people do not change the resolution much. 

Your rightmost monitor is the largest one, right? The seemingly lower capture speed is probably because InputScope reduces mouse movement events, first by scaling them to heatmap size and skipping those in the same location, and then by merging linear movement events that are close enough in time and space. 

If you like, there are some configuration directives you can add to [inputscope.ini](https://github.com/suurjaak/InputScope/blob/master/inputscope/var/inputscope.ini) to tweak the linear reduction:
- `MouseMoveJoinInterval` is maximum seconds between linear movement events to merge
- `MouseMoveJoinRadius` is maximum pixels between linear movement events to merge, in heatmap scale

Setting either to 0 will effectively disable the reduction of linear movement. Just add the directives to `inputscope.ini` when InputScope is not running. But be advised that there can be very many mouse movement events per second if they're not being reduced.
