### ISSUE TITLE
Heatmap itself is not representative

### ISSUE THREAD

**Issue by Quake4Life** [suurjaak/InputScope#32]
It woould be cool if the color grading could be set up differently because for now my scheme makes no sense with overused Spacebar and almost white "Q" with 4000+ presses
![image](https://github.com/suurjaak/InputScope/assets/121139390/03854b8b-6edc-43ff-b9d3-13fe158b4b16)

**Comment by suurjaak** [comment]
I suppose the color grading options could also be exposed in configuration file, so that they can at least be overridden by the user. For example, the current default heatmap settings are: blue from 25%, green from 55%, yellow from 85% and red from 100% (percentage being the ratio of a key count compared to the most frequent key count).

However, that would not really solve the problem, as one would need to start tailoring the settings to fit the data, but the data changes.. 

Maybe a solution would be to constrain the topmost one or two keys if they are way more frequent than the rest, then they would not skew the results so much.. 

Out of curiosity, what are the top 10 keys from your view? From some bigger data in my own logs, spacebar is 7th and the topmost is Left Ctrl:
![image](https://github.com/suurjaak/InputScope/assets/719382/82cce247-e9b4-4d12-a7b3-f99bb6fd4c79)

**Comment by Quake4Life** [comment]
My top ten certainly differs from yours since I'm russian and do not
program anything, the most frequently used keys are Space, J and T
[image: image.png]

пт, 12 апр. 2024 г. в 17:07, Erki Suurjaak ***@***.***>:

**Comment by suurjaak** [comment]
Btw, looks like the image attachment did not come through.

**Comment by suurjaak** [comment]
FYI, I'm currently experimenting with using a log scale for the keyboard heatmap, so that superfrequent keys do not fade out lesser keys so strongly. 

The result is looking much better for me. And, rather different as well, e.g. before:
![image](https://github.com/suurjaak/InputScope/assets/719382/f5369d27-f652-45fa-8d13-4bc510b8e01c)


vs after:
![image](https://github.com/suurjaak/InputScope/assets/719382/d414ae9c-09aa-49a1-b0ee-18c4bf8d5ccf)


I will tinker with this a bit and make a new release, in the not too far future.

**Comment by Quake4Life** [comment]
Very cool!
See näeb välja täpselt nii, nagu peaks, minu arvates

сб, 13 апр. 2024 г. в 19:41, Erki Suurjaak ***@***.***>:

**Comment by suurjaak** [comment]
The new v1.11 release should show the keyboard heatmap in better highlighting. 

Also, if you like, you can now override the heatmap colours. By specifying a custom gradient for heatmap display options in configuration file:

```javascript
HeatmapDisplayOptions = {"keyboard": {"gradient": {0.25: "blue", 0.55: "green", 0.85: "yellow", 1.0: "red"}}}
```

The numbers in gradient stand for percentage of total events; so in the default colouring above it starts from blue and ranges through green and yellow towards red. The colour can be any standard web colour, including colour codes like `"#FF0000"` or `"rgb(255, 0, 0)"`.

The heatmap display options can be applied to specific inputs like `"keyboard"` or `"mouse"`, more specific event types like `"combos"` or `"clicks"`, or to all heatmaps if given without nesting.

**Comment by Quake4Life** [comment]
Amazing, thank you :)

ср, 17 апр. 2024 г. в 20:35, Erki Suurjaak ***@***.***>:
