### ISSUE TITLE
Could be used as a key logger?

### ISSUE THREAD

**Issue by Myron-S** [suurjaak/InputScope#4]
I like the replay a bit as it gives me an idea of how, over time, I'm pressing keys.  There is one issue I've noticed that that the keys logged could be indirectly used by a threat actor to get usernames and passwords.  Data is stored unencrypted.

What would be a good idea is to make a side-version of the same program, but strip out the code and database structure that records each individual keystroke, so it counts key presses and key-combinations.

At the moment on VirusTotal only one scanning engine identifies your program as a threat which is Baidu.

**Comment by suurjaak** [comment]
It is frustratingly common for antivirals to tag packaged Python programs as malware. Either because PyInstaller uses similar techniques for packaging as some actual malware does, or just because their heuristics are superficial yet overeager. They've really became a bane for small independent software producers, I've had to fight them a number of times already. How it typically goes:

1. User reports that antivirus X says my program Y version Z is malware.
2. I inform antivirus X of false detection and upload the version Z binary for full analysis.
3. Antivirus X clears the false positive.
4. I release program Y version Z+1.
5. Go to step 1.

I requested a reanalysis on VirusTotal for InputScope, now Baidu reports it as all green, but SecureAge reports it as malicious. Like tilting at windmills.. Frustrating. 



---

However, it is true that a threat actor could use the database to obtain usernames and passwords. It would, of course, require the actor to have access to the user's system in the first place, in which case the user is already compromised anyway. 

I've looked into encrypting the SQLite database, but that is surprisingly complicated, requiring the use of custom libraries that have to be compiled by the user themselves if they want to use the source code version. Not really a path I want to go down. 

---

But yes, this program could be used as a key logger, because.. it is a key logger :) 

I suppose there could be a toggle option to record key counts only. This would, of course, get rid of the other detailed key statistics like typing speed, but I guess those are not that useful anyway.

**Comment by Myron-S** [comment]
Point taken.  My specific interest is over a 24 hour period what the frequency of key depressions there are.  It's mostly to determine wear on the keyboard. Your awesome program actually does this and does it well and those statistics can be collected without recording individual key presses.

I honestly would contribute to your project, but my time is occupied with a number of other tasks and projects.  I can give feedback and ideas from an end-user's and I.T. professionals perspective.

The key logging, though, is useful if not ever compromised.  I actually forgot something I typed this morning and recovered that using an SQL database browser.

**Comment by suurjaak** [comment]
> I actually forgot something I typed this morning and recovered that using an SQL database browser.

That is so cool :D

Btw, you can check out https://github.com/suurjaak/SQLitely for that. 

> I can give feedback and ideas from an end-user's and I.T. professionals perspective.

That would be rather useful indeed. 

How does that toggle option sound? It would be an additional item in the tray menu, something along the lines of "Stop individual key logging". And the main visual result would be no replay and no "keys per hour" etc on the statistics page. 

---

Also, maybe you have some idea how to mitigate the security threat? Because it has started to weigh on my mind a bit, especially in the context of passwords. E.g. stealing somebody's laptop does not necessarily give the thief access to the victim's online accounts. 

One option would be to at least not have the keys in complete plaintext in the database, but hashed or something, thereby removing the very low-hanging fruit. On the other hand, in a safe situation it's quite handy to be able to see your own input so plainly..

**Comment by Myron-S** [comment]
I was thinking along a threat actor's knowledge. All a hacker would need to do stumble across the SQL DB and steal a copy.

I guess a workaround would be to default the program when started not to log keystrokes and a human would need to enable keylogging. The option not to be remembered when InputScope is stopped.  This way the key press recording can never be enabled by accident or by a malicious program attempting to pretend to be a human enabling the key-press recording option..  Also,to  build in an option to erase either all individual key press statistics or over a user specified date range.

This may help in not having to encrypt the database and write in a disclaimer indicating that key presses are stored unencrypted.

Hope the feedback helps.

The daily counts summaries are indeed very useful.

**Comment by Myron-S** [comment]
I've just had another thought about who a _threat actor_ may be.  It does not have to be a unethical hacker but a toxic relationship.  What if a controlling partner in a relationship wishes to record keystrokes of the other partner and that partner is no that I.T. aware and does not realise that just about every key press is recorded?   Food for thought....

**Comment by suurjaak** [comment]
Mm, about the latter - there are plenty of available key loggers that are actually hidden from the user and provide the log in a much more convenient form than a relational database. If somebody has execute access to somebody else's computer, they can install and run whatever they choose. 

Anyway, defaulting to not recording detailed keystrokes sounds like a good approach to take. As does an option to clear history, that's something I've been thinking of myself. I have a database that has been populated for 5 months straight, and it's grown to 8 GB..

**Comment by Myron-S** [comment]
Yep, me over-reacting again.  :-)  Very true that someone determined to do this would find some way to implant some sort of key logger and there are many out there.

Back on topic...  I find that I am now really looking at the daily count statistics and daily heat-maps and I can see I will be rarely replaying key presses, but as I pointed out. There could be times where it would be useful to turn on key logging and turn it off on demand and as a security feature only a _human_ would be allowed to turn on key depression recording. (To make it very difficult or impossible for another program to invoke key press recording on your program.)

If anyone wants to always record their keystrokes then they'll just have to put up with enabling that function/feature each and every time your program is loaded and the keylogging function is allowed to remain in the enabled state between sleep and hibernate states.

Erasure of all recorded key strokes, and/or erasure of recorded key strokes between two times and dates would also be a good.  (What is the user ends up logging something by accident and would wish to, say, erase 14 minutes of key strokes within a day, an entire day hours or several days?)

I guess that mouse movements also grow the SQL database.  Would that require pruning at some point?  Maybe a user configurable option where mouse use data older then a user specified date gets automatically dropped dropped?  Hmmmm........   Maybe also offer the same option for recorded key presses.   Auto pruning?  If the user wants to keep all the recorded data, well, the auto-pruning would be a user settable option.

I think I'll give user feedbacking a rest for a while.  :-)  Hope it helps.

**Comment by suurjaak** [comment]
Ah, you meant that the key logging should be run-session-only. May be a good idea.. I was thinking of a permanent flag. Would certainly be more secure, but would also be less convenient if a user actually does want to  record all their keys, all the time. Will think about it. 

> I guess that mouse movements also grow the SQL database. 

Mouse movements make up the overwhelming bulk of the database. In that 8GB file of mine, mouse moves are 128M rows (96% of database size), while scrolls are 3M rows, clicks 1.5M rows, and keys <1M rows. Every little move event is an additional row. 

Not sure if I want to add auto-pruning.. It would introduce a good amount of complexity. 

A better option might be to add toggles for disabling moves/scrolls/clicks and keys/combos individually. Which is one reason against the run-session-only key logging toggle, as it would have different logic. 

I think I will add a small tray notice popup on program startup, that announces what is being logged. Just a little extra thing against unwanted use.

**Comment by suurjaak** [comment]
Released v1.3. 

Added individual toggles for event types. And various options to clear history from the database. And a tray notice popup on program startup, announcing what is being logged. 

Decided against defaulting to not recording detailed keystrokes. Will maybe add an option in the next release to record key counts only,
