### ISSUE TITLE
v1.3 and v1.4 are being detected as malware

### ISSUE THREAD

**Issue by shenef** [suurjaak/InputScope#7]
When downloading, Chrome flagged it as not trusted (which happens to me all the time) but today Windows flagged it after a reboot.

VirusTotal:
https://www.virustotal.com/gui/file/f7c3f5e58e0a3c984f05a04dcc29dffc8ff137485d29c1f7448c300b28fd03e7

Windows Security:
![image](https://user-images.githubusercontent.com/20268890/106499768-4a1fdd00-64c1-11eb-8529-efab85d543e9.png)

I guess something the program does trips the malware detection.

**Comment by suurjaak** [comment]
Sigh.. here it goes again. Antivirals seem to have a real hatred for packaged Python programs :) It's been an issue I've frequently had to deal with, as the initial scan they do is superficial, but ends up in virustotal and other places. 

I've reported the false positive to Microsoft, SecureAge and SangFor for re-analysis. I could not report to eGambit.. because their submission page simply does not work. 

Thank you for informing me of this.

**Comment by suurjaak** [comment]
I've been reporting this false positive to some of the antivirals, but they all take their sweet time in processing the reports..

**Comment by suurjaak** [comment]
Finally got a reply from SecureAge: 

> Our review team has looked at your program's source code and did not find any malicious indicators, thus we will clear the detection on this version of your program. However, as it is marked by Microsoft Smartscreen and numerous other vendors, we cannot guarantee that future versions of your software will be cleared; in that case, you would need to resubmit future versions of your program to our submission portal. We ask for your kind understanding in this matter

> Your false detection(s) will be cleared within the next 72 hours; please reply to us if that is not the case. For APEX results on VirusTotal, false detections may take additional time to clear. You may need to reanalyze files in order to get the updated detection result.

Nothing at all from the other antivirals yet.

**Comment by suurjaak** [comment]
Situation with the antivirals continues to be quite hopeless, but closing this issue as outdated.
