### ISSUE TITLE
Very fast mouse scrolling causes a beeping sound and mouse lag

### ISSUE THREAD

**Issue by shenef** [suurjaak/InputScope#8]
It only happens when using a free scrolling mouse wheel (MX Master 2S).
Some googling showed that it is most likely caused by overloading the mouse driver with too many inputs.
This also happened on version 1.1 but there it was triggered by a much slower scroll speed.
It disappears when turning off InputScope or disabling mouse logging but it still happens when i enable mouse event categories separately, so it doesn't seem to be tied to one of those.

**Comment by suurjaak** [comment]
Sounds like that mouse is creating so many events when scrolling, that even just listening to them causes a massive load - as the underlying input hook library subscribes to all mouse events. 

If you open up the statistics page, how many events does a single scrolling generate?

**Comment by shenef** [comment]
Giving it a solid spin and then letting it roll for 3 seconds produced 190 to 230 events.
Letting it roll until it stops by itself creates 1500 to 1600 events.

**Comment by suurjaak** [comment]
That is.. quite a lot of events for scrolling :) I should add functionality that combines rapid consecutive scroll events into one. 

But the lag here is not due to not combining the events, as they're not written to database anyway if the scroll category has been disabled. So it looks like the input library I use, perhaps cannot handle a free-scrolling mouse wheel well.. 

I've been eyeing another library for a while already, as development and support has stopped on the current one I use. 

It would be interesting to know whether the newer library works properly with a free-scrolling mouse. Could I give you two small test programs to run, one using the older and other the newer library, that would simply listen to scroll events and report their count at exit? If the older library causes lag with a free-scrolling mouse and the newer one doesn't, then it is reason enough to switch InputScope to the new library. 

Or, if you have some experience with Python, I could send you the source code of those two small test programs.

**Comment by shenef** [comment]
Sure, i can test those programs for you. I don't have much experience with python but i guess i'll manage executing the source code.

**Comment by suurjaak** [comment]
Here they are, both as source code and as already compiled programs, whichever you prefer. 

For running the Python source code, you would need to do `pip install pyuserinput` before running `python test_pyuserinput.py`, and `pip install pynput` before running `python test_pynput.py`.

[tests.zip](https://github.com/suurjaak/InputScope/files/5919772/tests.zip)

**Comment by shenef** [comment]
pynput seems much better.
No beeps, no mouse lag, pretty much the same CPU usage, smaller executable and most importantly - same result as pyuserinput and the current InputScope version.

pyuserinput has the same problems as the current InputScope build, Beeps and mouse lag.

**Comment by suurjaak** [comment]
Excellent, that settles it. Need to start using pynput. 

Thank you.

**Comment by suurjaak** [comment]
The new v1.4 release now uses pynput. Can you confirm that the lag issue no longer occurs with mouse scrolling?

**Comment by shenef** [comment]
Can confirm 1.4 fixes the beeping and lag when doing very fast mouse scrolls.
It also looks like scroll events are being combined, free scrolling registers as 1-3 events instead of hundreds.

**Comment by suurjaak** [comment]
Excellent, pynput is working so much better. 

And yes, scroll events in the same direction and close in time are combined. The statistics page shows the combined scroll counts at the bottom.
