### ISSUE TITLE
On old DB v1.4 stops collecting if inputscope.db-wal reaches >1024 KB

### ISSUE THREAD

**Issue by shenef** [suurjaak/InputScope#9]
This happened when using my old 900+ MB database. Restarting InputScope or repacking the DB did not solve it.
When using a new database it seems to work correctly.
Is there some sort of logging i can enable to see what could cause that?

**Comment by suurjaak** [comment]
There is no easy way to see logging with the compiled binary. 

Perhaps the case is simply that SQLite has queued the database changes it needed to do on the old database, but has not yet completed doing them? There were some schema changes on existing tables, those get queued to SQLite's write-ahead log (that's what the .db-wal file is) and carried out in the background. With a large database, the changes might take a while. 

What happens if you let InputScope run for a while? Preferably with input logging disabled, so that there are no other constant writes.

**Comment by shenef** [comment]
Letting it run without logging doesn't solve the problem. Another thing i noticed is that the 1024KB is only true for my work PC with the big DB. At home with a smaller DB the file reaches a max of 4096 KB and continues to write into the DB but if there is too much activity then it seems to stop working.
It seems like 1.4 doesn't really work well with a 1.3 or older DB. I can make it lock up pretty much instantly by free-scrolling while starting the program. But if i let it create a new DB, then all of those problems disappear.

**Comment by suurjaak** [comment]
Found the problem - there was a bug in the database schema update. 

I've put up InputScope v1.4.1 where this should be fixed.

**Comment by shenef** [comment]
can confirm that this has been fixed in v1.4.1
